Win condition
DanielPri/XrudderAI pull request #5
Opened 2019-10-11 14:53 UTC by PinMeister

Hopefully, everything should work now!

2019-10-11 15:08 UTC, Songtone requested changes

2019-10-11 15:08 UTC, Songtone commented on Game.py
> +            self.win_condition(self.player2)
Is it possible to only have the win condition check  when the player has at least 5 pieces on the board? Also, can we have only one call that checks both players instead of calling win_condition twice.

2019-10-11 15:08 UTC, Songtone commented on Game.py
> +            self.win_condition(self.player1)
same as above

2019-10-11 15:08 UTC, Songtone commented on Game.py
> +        letter_array = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]
Can we get the letters straight from the letter_map instead of hard coding it here

2019-10-11 15:08 UTC, Songtone commented on Game.py
> +        else:
The code is the same as above. Can we refactor it to one code. It could check both player one after the other. Also, do we have a check where if both player get a win after a move, that the last player to make a move is the winner?

2019-10-11 15:08 UTC, Songtone commented on Game.py
> +                            print(str(self.player2.name) + " wins!")
I think this should be player1

2019-10-11 15:08 UTC, JamalG16 requested changes

2019-10-11 15:08 UTC, JamalG16 commented on Game.py
> +                exit(0)
pls break out of the loop instead of using exit

2019-10-11 15:08 UTC, JamalG16 commented on Game.py
> +        m = 1
please use more descriptive variable name (please rename n as well)

2019-10-11 15:17 UTC, JamalG16 requested changes

2019-10-11 15:17 UTC, JamalG16 commented on Player.py
> +        elif len(self.played_pieces) == 15:
pls declare a variable called max_pieces or something at the class level and compare against that for readability

2019-10-11 15:17 UTC, JamalG16 commented on Player.py
> +            if moves < 30:
same thing as the max_pieces comment, declare a class variable or something and use that for comparison for readability

2019-10-11 15:22 UTC, PinMeister commented
I'll admit I forgot about the 5 pieces rule.

The reason for checking win condition twice for each player is due to this: 
"If a player gets a regular X formed and results also in another regular X for the other player,
putting them both in a winning configuration, then only the player who played the last token
wins the game. "

We must account for the fact that the win condition for the player who played the last token must be checked before the other. This also applies if they move a piece that makes the other player win, which requires the other player to be checked in the same turn.

2019-10-11 15:24 UTC, PinMeister commented on Game.py
> +                            print(str(self.player2.name) + " wins!")
No, strikethrough is white, so if that doesn't occur, black (player 2) wins.

2019-10-11 15:25 UTC, Songtone commented
Why not have it check if they last played a piece when checking the win condition.

2019-10-11 15:25 UTC, JamalG16 commented
> I'll admit I forgot about the 5 pieces rule.
> 
> The reason for checking win condition twice for each player is due to this:
> "If a player gets a regular X formed and results also in another regular X for the other player,
> putting them both in a winning configuration, then only the player who played the last token
> wins the game. "
> 
> We must account for the fact that the win condition for the player who played the last token must be checked before the other. This also applies if they move a piece that makes the other player win, which requires the other player to be checked in the same turn.

It's also worth to mention that if player 1 PLACES a piece, then there is no way player 2 can win the game and thus only player 1's win condition must be checked because checking player's 2 win condition is useless.The only time you should check win condition of both players is if a piece is moved, and as you said, in the right order.

2019-10-11 15:40 UTC, PinMeister commented on Game.py
> +            self.win_condition(self.player2)
> > I'll admit I forgot about the 5 pieces rule.
> > The reason for checking win condition twice for each player is due to this:
> > "If a player gets a regular X formed and results also in another regular X for the other player,
> > putting them both in a winning configuration, then only the player who played the last token
> > wins the game. "
> > We must account for the fact that the win condition for the player who played the last token must be checked before the other. This also applies if they move a piece that makes the other player win, which requires the other player to be checked in the same turn.
> 
> It's also worth to mention that if player 1 PLACES a piece, then there is no way player 2 can win the game and thus only player 1's win condition must be checked because checking player's 2 win condition is useless.

The app exits if player 1 wins, therefore player 2's win condition is never checked.

2019-10-11 16:30 UTC, PinMeister commented on Game.py
> +                            print(str(self.player2.name) + " wins!")
I did spot a typo elsewhere though

2019-10-15 20:10 UTC, DanielPri approved these changes
nice job fixing the bugsos

2019-10-16 02:05 UTC, Songtone requested changes
Other than a couple of details, it looks very good the win condition check! Good job!

2019-10-16 02:05 UTC, Songtone commented on Game.py
> +                        self.game_over = True
minor detail, you can draw the board to display to the user the board that shows the winning X.

2019-10-16 02:05 UTC, Songtone commented on Game.py
> +                        self.game_over = True
same as above

2019-10-16 02:05 UTC, Songtone commented on Game.py
> +        letter_array = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]
you can use 
for key in letter_map.keys():
   letter_array.append(key)

2019-10-16 06:47 UTC, Songtone approved these changes
Good job!

2019-10-16 16:44 UTC, JamalG16 requested changes

2019-10-16 16:44 UTC, JamalG16 commented on Game.py
> +                    self.win_condition(self.player2.played_pieces)
if player places a piece, then the number of moves is not incremented, correct? If so, then can you check that if the number of moves hasn't incremented, then do not check the win condition of player 2 please. The reason for this is that if player 1 places a piece, then there is no way player 2 can win and vice versa. Hence, checking win condition for the other player when a player places a piece is useless.

2019-10-16 16:44 UTC, JamalG16 commented on Game.py
> +
same as above.

2019-10-16 16:44 UTC, JamalG16 commented on Game.py
> +                        print("Strikethrough at black X centered at " + str(iterated_piece) + "!")
Each player has their own played_pieces if I'm not mistaken, so what you could so is pass the tile color as a parameter in the method (win_condition(player.played_pieces, player.color)). This way you don't need to check both black and white, you could just complete the check for the color passed as param.

2019-10-16 17:40 UTC, PinMeister commented on Game.py
> +                        print("Strikethrough at black X centered at " + str(iterated_piece) + "!")
This code only serves to print the correct messages for strikethroughs and who wins.

2019-10-16 17:47 UTC, JamalG16 commented on Game.py
> +                        print("Strikethrough at black X centered at " + str(iterated_piece) + "!")
Yes I agree, but you're passing a specific player's pieces as a parameter. If you're passing player 1 pieces as the parameter and player 1 is white, then is there a point in having the code that checks for the black pieces?

2019-10-16 18:50 UTC, JamalG16 commented on Game.py
> +                self.win_condition(self.player1.name, self.player1.played_pieces, TileColor.WHITE, TileColor.BLACK)
looks good! only thing I would suggest is instead of hard coding the tilecolors as params, you could do player.color and for the opponent color you could add a method in tilecolor to get the opposite color and then you could pass in tilecolor.getOppositeColor(player.color).

2019-10-16 18:52 UTC, JamalG16 commented on Game.py
> +                self.win_condition(self.player1.name, self.player1.played_pieces, TileColor.WHITE, TileColor.BLACK)
Or you could even just pass in the player's color and opponent player's color

2019-10-16 19:09 UTC, JamalG16 approved these changes

2019-10-16 19:10 UTC, merged